### ISSUE TITLE
Eject button coords

### ISSUE THREAD

**Issue by krpandit** [chaichontat/pyseq2501-web#1]
in /src/components/sidebar)/mapp.svelte line 53
`$cmdStore = { move: { xy0: [0, -7.5] } };`

The eject button moves the stage all the way to the right and keeps at 0 in the y direction.
The y stage min range in pyseq2501 is -7e6, which is why it doesn't move in the y direction.

The stage should be moved to 30000, -7e6 or 30000, -7.5e6  if you also want to update the min y range.

**Comment by chaichontat** [comment]
Actually the unit there is in mm relative to the current flowcell. The rule is that all units including and below `Imager` and `Flowcells` are in instrumental units and all units (`Experiment` and web) above are in real world units.

I didn't calculate the actual eject position in mm and just put this in as an estimate. Although, the limit on my HiSeq seems to be at around -6.8e6, going beyond that resets the stage.

**Comment by krpandit** [comment]
Just tried ejecting again. The A eject pushed the stage up against some of the door wires. The y stage disengaged when I tried ejecting to the B position (from the A eject position). Just eyeballing the x B flowcell eject position, it might run into the reagent slot in the HiSeq2500 door if the y stage pushed out. 

I don't think the eject button should be tied to the flowcell. I think it makes more sense to eject the stage out so both flowcells are readily accesible. It would also simplify the ejecting the stage on the 2500 side.

**Comment by chaichontat** [comment]
I just added a "correction" factor to the x-coord so that the stage will always eject toward the center.

The architecture is such that all external APIs to `pyseq2` communicate in real-world units. Changing its internal state directly would break encapsulation. The eject button is the only place in the interface whose move command is not a function of the operating flow cell.

**Comment by krpandit** [comment]
Just tested, this is much better thanks!
