### ISSUE TITLE
Select inlet ports on HiSeq2500

### ISSUE THREAD

**Issue by krpandit** [chaichontat/pyseq2501-web#2]
There needs to be a way to configure a HiSeq2500 to use the 8 or 2 port inlet. 

Should this be done in the config file? Or should there be a toggle switch in the fluidics sidebar and flowcell experiment design?

**Comment by chaichontat** [comment]
Do people switch inlet ports in one session? If not, then this should be relegated to config files.

**Comment by krpandit** [comment]
They don't need to switch inlet ports in one session. But they should be made aware which inlet port is being used.

So maybe just an icon displaying which port is being used is what we need.

And if a user realizes the wrong port is being used, can they change the inlet port in the config file at runtime and then reinitialize?

**Comment by chaichontat** [comment]
A floating icon would probably make no sense. If we're including the indicator, might as well make it controllable.
